### PR TITLE
fix(docs): remove stale zod v3 overrides breaking Astro 6 build

### PR DESCRIPTION
**Pull request by jsell-rh**
## Summary

- Remove `zod` and `@astrojs/sitemap` npm overrides that were workarounds for Astro 5

## Problem

#1539 bumped Astro from v5 to v6. Astro 6 imports `zod/v4` (native Zod v4 API), but the `zod: "3.25.76"` override forced a v3 compat shim. The v3 shim exposes `zod/v4` with the native v4 API where `z.function().optional` doesn't exist, causing the Netlify build to crash:

```
z.function(...).optional is not a function
  at astro/dist/content/utils.js:86:12
```

This has been breaking Netlify deploy previews on every PR since #1539 merged.

## Fix

Remove the `zod` and `@astrojs/sitemap` overrides — both were workarounds for the Astro 5 + `@astrojs/sitemap@3.7` Zod conflict (#1223) and are no longer needed with Astro 6, which expects native Zod v4 (`^4.3.6`).

## Test plan

- [x] `npm run build` passes — 29 pages, 0 errors
- [x] `npm run dev` serves correctly on localhost
- [x] Mermaid diagrams render (Playwright chromium installed)
- [x] Zod resolves to `4.4.3` (proper v4), Astro stays at `6.3.1`

🤖 Generated with [Claude Code](https://claude.ai/code)

## Summary by CodeRabbit

* **Chores**
  * Updated dependency override configurations in the documentation package.

### CODE REVIEW

**Review by markturansky — APPROVED** [review]
LGTM

**Comment by jsell-rh** [comment]
@mergifyio queue
